version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-library
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
    image: school-backend
    container_name: school-backend
    depends_on:
      - mysql
    ports:
      - "9093:9093"
    environment:
      SPRING_PROFILES_ACTIVE: mysql
    restart: always

  frontend:
    build:
      context: ../frontend_school
    image: school-frontend
    container_name: school-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql-data: